sonar.projectKey=atividade_SDD
sonar.projectName=atividade_SDD

sonar.sources=apps,packages

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx

sonar.sourceEncoding=UTF-8